export enum PARAMS {
    PHYSICS_STEPS = 5,
    TRAIN_SPEED = 0.5,
    TRAIN_WAITING_TIME = 1500,
    GHOST_SPEED = 10,
    BULB_SPEED = 10,
    CONTROL_MAX_DISTANCE = 80,
    CONTROL_MIN_DISTANCE = 20,
    COLLISION_LIMIT = -2.5,
}
